name: acpype
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - acpype
  - ambertools
  - openmm
  - biopython
  - numpy
  - scipy
  - pandas
  - matplotlib
  - networkx
  - mdanalysis
  - mdtraj
  - prolif
  - rdkit
  - openbabel
  - scikit-learn
  - pdbfixer
  - seaborn
  - tqdm
  - pip
  - pip:
      - amberutils==21.0
      - edgembar==3.0
      - mmpbsa-py==16.0
      - openbabel-wheel==3.1.1.22
      - packmol-memgen==2025.1.29
      - pdb4amber==22.0
      - pymsmt==22.0
      - pytraj==2.0.6
      - sander==22.0
